# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca7bff2a5656c3f6f05fcbeaa8f6a1a63967c144b9cd337c1fd9fd5dfb62ad8ae8f01874f80076b0f9b18a3f8919644e475f97a315eb40c693d357372158188d

test:
  secret_key_base: 6642aa9959fe500e4bc27f90ebf8ecde47fe6bde85ccf9026fa9a58471d34a6d0d544cc3ae9551e88ac382cbb2da519499fcd280a7846c1d070b2374f87a7d11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
